exp:
  name: sparc_ppo_longctx
data:
  datasets: [narrativeqa, hotpotqa]  # Multiple datasets to use
  split: train
env:
  chunk_size: 256
  max_window: 2048
curriculum:
  enabled: true
  start_chunks: 2
  max_chunks: 10
  growth_steps: 50_000
model:
  tokenizer: NousResearch/Meta-Llama-3.1-8B
  embed_dim: 128
  vocab_size: 128256
  net_arch: [{pi: [128, 64], vf: [128, 64]}]
train:
  n_envs: 8
  total_steps: 1_000_000
  lr: 3e-5
  n_steps: 1024
  batch_size: 256
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
wandb:
  project: SPARC
eval:
  frequency: 10   # Evaluate every 10k steps
  episodes: 20      # Number of episodes to evaluate on
  deterministic: true
